#!/usr/bin/env bash

# startup application on first launch only
. ${HOME}/.config/herbstluftwm/startup

# load custom colorscheme
. ${HOME}/.cache/themes/current.sh

# create alpha variations of colors
alpha='EF'
mod_color1="${color1}${alpha}"
mod_color3="${color3}${alpha}"
mod_color4="${color4}${alpha}"
mod_color5="${color5}${alpha}"
mod_color8="${color8}${alpha}"

hc() {
  herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Alt=Mod1
Super=Mod4

hc keybind $Super-Shift-q quit
hc keybind $Super-Shift-r reload
hc keybind $Super-Shift-c close

hc keybind $Super-Return spawn kitty
hc keybind $Super-e spawn pcmanfm
hc keybind $Super-p spawn launchers rofi -theme launcher 
hc keybind $Super-Shift-e spawn kitty --class "nvim" -e "nvim"

hc keybind $Super-Shift-n spawn pkill -USR1 redshift

# basic movement in tiling and floating mode
hc keybind $Super-h focus left
hc keybind $Super-j focus down
hc keybind $Super-k focus up
hc keybind $Super-l focus right

# moving clients in tiling and floating mode
hc keybind $Super-Shift-h shift left
hc keybind $Super-Shift-j shift down
hc keybind $Super-Shift-k shift up
hc keybind $Super-Shift-l shift right

# splitting frames
hc keybind $Super-u split bottom 0.5
hc keybind $Super-o split right 0.5

# let the current frame explode into subframes
hc keybind $Super-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Super-Control-h resize left +$resizestep
hc keybind $Super-Control-j resize down +$resizestep
hc keybind $Super-Control-k resize up +$resizestep
hc keybind $Super-Control-l resize right +$resizestep

# tags
tag_names=( {1..6} )
tag_keys=( {1..6} )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if [ -n "$key" ] ; then
    hc keybind "$Super-$key" use_index "$i"
    hc keybind "$Super-Shift-$key" move_index "$i"
  fi
done

# cycle through tags
hc keybind $Super-period use_index +1 --skip-visible
hc keybind $Super-comma use_index -1 --skip-visible

# layouting
hc keybind $Super-r remove
hc keybind $Super-s floating toggle
hc keybind $Super-f fullscreen toggle

hc keybind $Super-Shift-f set_attr clients.focus.floating toggle
hc keybind $Super-Shift-d set_attr clients.focus.decorated toggle

hc keybind $Super-Shift-m set_attr clients.focus.minimized true
hc keybind $Super-Control-m jumpto last-minimized
hc keybind $Super-Shift-t pseudotile toggle

hc keybind $Super-space \
  or , and . compare tags.focus.curframe_wcount = 2 \
  . cycle_layout +1 vertical horizontal max vertical grid \
  , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Super-Button1 move
hc mousebind $Super-Button2 zoom
hc mousebind $Super-Button3 resize

# focus
hc keybind $Super-BackSpace cycle_monitor
hc keybind $Alt-Tab cycle_all +1
hc keybind $Alt-Shift-Tab cycle_all -1
hc keybind $Super-c cycle
hc keybind $Super-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 0
hc set frame_border_active_color ${mod_color4:='#222222cc'}
hc set frame_border_normal_color ${mod_color3:='#101010cc'}

hc set frame_bg_normal_color '#565656aa'
hc set frame_bg_active_color '#345F0Caa'

hc set frame_gap 4
hc set frame_transparent_width 0
hc set frame_bg_transparent on
hc set show_frame_decorations 'focused_if_multiple'

hc attr theme.title_depth 4
hc attr theme.title_height 16
hc attr theme.title_align center
hc attr theme.title_when multiple_tabs
hc attr theme.title_font 'JetBrains Mono:pixelsize=16'

hc attr theme.title_color ${color8:='#ffffff'}
hc attr theme.normal.title_color ${color8:='#898989'}
hc attr theme.active.tab_title_color ${color15:='#ababab'}

hc attr theme.active.color ${mod_color4:='#345F0Cef'}
hc attr theme.active.inner_color ${color4:='#789161'}

hc attr theme.normal.color ${mod_color3:='#323232dd'}
hc attr theme.normal.inner_color ${color3:='#606060'}

hc attr theme.urgent.color ${mod_color1:='#7811A1dd'}
hc attr theme.urgent.inner_color ${color1:='#9A65B0'}

hc attr theme.tab_color ${mod_color8:='#1F1F1Fdd'}
hc attr theme.active.tab_color ${mod_color8:='#2B4F0Add'}
hc attr theme.active.tab_outer_color ${mod_color4:='#6C8257dd'}

hc attr theme.border_width 0
hc attr theme.inner_width 0
hc attr theme.inner_color black

hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black

# copy inner color to outer_color
for state in active urgent normal ; do
  hc substitute C theme.${state}.inner_color \
    attr theme.${state}.outer_color C
done

hc attr theme.tiling.outer_width 0
hc attr theme.background_color '#141414'

hc set window_gap 12
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=on
hc rule floatplacement=smart
hc rule fixedsize floating=on

#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule class='Pcmanfm' floating=on
hc rule class='Tint2conf' floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
